name: Add Team
description: Proposer l'ajout d'une team FR dans les regex et Custom Formats
title: "[Team]: "
labels: ["type: team"]

body:
  - type: input
    id: team-name
    attributes:
      label: Nom de la team
      placeholder: "Ex: BOUBA"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Ce qu'elle propose principalement
      options:
        - Remux
        - UHD Bluray
        - HD Bluray
        - WEB-DL / WEBRip
        - HDLight
        - Anime
        - Scene
        - Global / généraliste
        - LQ / à bannir
        - Inconnu
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Exemples de releases
      description: Ajoute plusieurs noms complets si possible.
      placeholder: |
        Movie.2026.FRENCH.1080p.WEB.H264-TEAM
        Show.S01E01.MULTI.2160p.WEB.H265-TEAM
    validations:
      required: true

  - type: dropdown
    id: suggested-tier
    attributes:
      label: Tier proposé
      options:
        - Film/Série Tier 1
        - Film/Série Tier 2
        - Film/Série Tier 3
        - Anime Tier 1
        - Anime Tier 2
        - Anime Tier 3
        - Anime FanSub
        - À bannir
        - Autre (précisez dans notes : nouveau Tier, plusieurs Tiers...)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      value: |
        Qualité habituelle, sources, réputation, liens utiles...

        Encode spécifique :
        - Release 4K toujours en h265 :
        - Uniquement HDLight / 4KLight :
        - Autre élément utile pour trier la team :

        Si la team doit aller dans un tier à gros score avec neutraliseur, ajoutez les détails utiles ici.
