name: Change Score
description: Demander un changement de score pour un Custom Format dans un profil
title: "[Score]: "
labels: ["type: scoring"]

body:
  - type: input
    id: custom-format
    attributes:
      label: Custom Format concerné
      placeholder: "Ex: FR Global Tier 01"
    validations:
      required: true

  - type: input
    id: profile
    attributes:
      label: Profil concerné
      placeholder: "Ex: 1080p Efficient FR"
    validations:
      required: true

  - type: input
    id: current-score
    attributes:
      label: Score actuel
      placeholder: "Ex: 99000"
    validations:
      required: false

  - type: input
    id: requested-score
    attributes:
      label: Score souhaité
      placeholder: "Ex: 100000"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Pourquoi changer ce score ?
      placeholder: "Explique le problème de priorisation ou donne un exemple concret."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Releases exemples
      placeholder: "Ajoute des releases qui montrent le problème de score."
